### ISSUE TITLE
Settings don't update workers until a restart

### ISSUE THREAD

**Issue by OmgImAlexis** [Josh5/unmanic#65] opened 2019-08-11 01:57 UTC
### Description
Settings doesn't change reflect worker number change until app restart.
Changing the setting back to 3 allowed to me start a third job without an issue. Once these are all done I'll test again to ensure this is the issue.

### Steps to Reproduce

1. Start app (3 workers)
2. Start 2 jobs
3. Change workers to 2
4. Crash on next job

**Expected behavior:** [What you expect to happen]
No crash

**Actual behaviour:** [What actually happens]
Crash

**Reproduces how often:** [What percentage of the time does it reproduce?]
Need to test more.

### Versions
`0.0.1-beta5~34b50f6`

### Installation Method Used
Docker

Manually installed and run or run through Docker?
Docker

```
2019-08-11T01:50:13:ERROR:Unmanic.Worker-0 - [FORMATTED] - Exception in processing job with Worker-0: - ['ffmpeg', '-y', '-i', '/library/All.Dogs.Go.to.Heaven.2.1996.1080p.BluRay.DTS.x264-Skazhutin.mkv', '-hide_banner', '-loglevel', 'info', '-strict', '-2', '-max_muxing_queue_size', '512', '-map', '0:0', '-map', '0:1', '-map', ' 0:1', '-map', '0:2', '-map', '0:3', '-map', '0:4', '-c:v', 'libx265', '-c:a:0', 'copy', '-c:a:1', 'aac', '-b:a:1', '128k', '-ac', '2', '-metadata:s:a:1', "title='Stereo'", '-c:s:1', 'copy', '-c:s:2', 'copy', '-c:v', 'libx265', '-y', '/tmp/unmanic/file_conversion-1565488205.6513975/All.Dogs.Go.to.Heaven.2.1996.1080p.BluRay.DTS.x264-Skazhutin-1565488205.651413.mkv']
Traceback (most recent call last):
  File "/app/lib/worker.py", line 176, in run
    self.process_task_queue_item()
  File "/app/lib/worker.py", line 157, in process_task_queue_item
    self.current_task.success = self.process_item()
  File "/app/lib/worker.py", line 139, in process_item
    ffmpeg_args)
  File "/app/lib/ffmpeg.py", line 510, in convert_file_and_fetch_progress
    raise FFMPEGHandleConversionError(command)
lib.ffmpeg.FFMPEGHandleConversionError: ['ffmpeg', '-y', '-i', '/library/All.Dogs.Go.to.Heaven.2.1996.1080p.BluRay.DTS.x264-Skazhutin.mkv', '-hide_banner', '-loglevel', 'info', '-strict', '-2', '-max_muxing_queue_size', '512', '-map', '0:0', '-map', '0:1', '-map', ' 0:1', '-map', '0:2', '-map', '0:3', '-map', '0:4', '-c:v', 'libx265', '-c:a:0', 'copy', '-c:a:1', 'aac', '-b:a:1', '128k', '-ac', '2', '-metadata:s:a:1', "title='Stereo'", '-c:s:1', 'copy', '-c:s:2', 'copy', '-c:v', 'libx265', '-y', '/tmp/unmanic/file_conversion-1565488205.6513975/All.Dogs.Go.to.Heaven.2.1996.1080p.BluRay.DTS.x264-Skazhutin-1565488205.651413.mkv']
```

**Comment by Josh5** [comment] 2019-09-29 06:57
How did you get on retesting this?

**Comment by OmgImAlexis** [comment] 2019-09-29 07:17
From memory this still is an issue. I haven't used this in a while though.

**Comment by Josh5** [comment] 2019-10-08 07:10
I'm unable to reproduce this on the latest release. 
If you are unable to retest or reproduce I will just close this issue.

**Comment by Josh5** [comment] 2019-10-15 05:15
Tested with modifications made in commit 676dc4831fa Everything working fine so closing issue

**Closed by Josh5** 2019-10-15 05:15 UTC
Labels: potential bug, question
