### ISSUE TITLE
Feature Request - 

### ISSUE THREAD

**Issue by shadowtor** [Josh5/unmanic#53] opened 2019-07-08 13:47 UTC
A good setup for this would be to watch the completed downloads folder, convert files that are downloaded (if they do not require conversion, so simply submit as 'completed' to then push a notification/PPscript to sonarr/radarr on completion to grab the file and send it where it needs to go (e.g. Plex Library folders)
Currently on this setup, most items would need to be manually converted

**Comment by Josh5** [comment] 2019-09-29 06:08
I'm not really sure what this is about. Not sure what "setup" you are referring to. You can point this at a downloads folder if you wish, however, the point of this application is to automatically standardise the format of your current media library and any new files added to it.

I'm closing this issue as at best it is a duplicate of issue #31

**Closed by Josh5** 2019-09-29 06:08 UTC
