### ISSUE TITLE
Use of FFMPEG Python Package

### ISSUE THREAD

**Issue by Dr-Crow** [Josh5/unmanic#61] opened 2019-07-24 19:15 UTC
### Description

I've been looking over the `ffmpeg.py` file and started to think that we are recreating the wheel. There are many projects that use ffmpeg in python and after some digging I found that there is a couple python packages that act as a wrapper for ffmpeg. That is basically what your `ffmpeg.py` is doing, acting as a wrapper to call fmpeg from Linux command line. 

After reviewing the couple python packages, I would suggest we look into the possibility of using [ffmpeg-python](https://github.com/kkroening/ffmpeg-python). Here are some examples of how to use the package, https://github.com/kkroening/ffmpeg-python/tree/master/examples.

### Additional Information

Some advantages to utilizing a python package for ffmpeg:
- No need to write complex PyTest, as they do already
- Can focus on writing our python package and extending the default ffmpeg package to fit our needs
- Let the package handle all ffmpeg updates and the corresponding python wrappers that need to be written

But there are some disadvantages as well:
- The python package might not handle all the flags/settings we want to use
- Relying on another package to push updates in a timely manor is sometimes hard

I personally think using the module above would be a smart move. The biggest advantage is allowing use to focus on the core issue of this project, instead of trying to maintain this project(UI, API, DB, etc) and a ffmpeg wrapper. 

**Note:** There are a couple other wrappers/packages for python that deal with ffmpeg but I did not think they were updated often enough/better then the one I listed above. But who knows, it might be worth checking them out too.

- https://pypi.org/project/ffmpy/ (looks okay)
- https://pypi.org/project/ffmpeg/ (idk about this one)

**Comment by Josh5** [comment] 2019-07-27 00:13
The plan at the moment for unmanic is to break out the container selection, video encoders, audio encoders and subtitle settings out of ffmpeg.py. ffmpeg.py should only be building the arguments, running the conversion and providing status of that conversion process for the workers to read. The problem is that certain combinations of mux/video enc/audio enc/subtitle are not possible. These need to be caught outside of ffmpeg.py. If you believe you can make ffmpy or something similar work in a way that slots in with these conditions, then be my guest. I personally do not see how maintaining a custom ffmpeg wrapper for unmanic is fine. But I'm biased because I've written it :).

I think this should be lowered on the priority tho. It would be best to wait until after all the other things are completed.

**Comment by Dr-Crow** [comment] 2019-07-27 00:16
You can check out my fork, I started replacing the command line ffmpeg with the module.

I need to create another branch though, before you can merge the docker stuff.

**Comment by Josh5** [comment] 2019-10-08 07:05
Did you make any progress with the FFMPEG python modules?
At the moment I think Unmanic works best with a custom library for this. It's easy enough to maintain.

**Comment by Josh5** [comment] 2020-10-22 18:08
Closing issue as no progress was made and unmanic's python module provides better functionality

**Closed** 2020-10-22 18:09 UTC
Labels: question
