### ISSUE TITLE
Add ability for Hardware encoding utilizing the Nvidia driver now available in unraid.

### ISSUE THREAD

**Issue by darrenjjeffries** [Josh5/unmanic#38] opened 2019-05-14 11:37 UTC
It would be really helpful to use the GPU for encoding

**Comment by dslowder** [comment] 2019-05-15 14:07
This is a duplicate of: https://github.com/Josh5/unmanic/issues/28

**Comment by Josh5** [comment] 2020-10-20 20:13
Done

**Closed by Josh5** 2020-10-20 20:13 UTC
Labels: duplicate, enhancement
